
const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3001;
// Serve static files (frontend)
app.use(express.static(path.join(__dirname)));


// In-memory data: All countries, capitals, and a famous place
const items = [
  { country: 'Afghanistan', capital: 'Kabul', famousPlace: 'Blue Mosque' },
  { country: 'Albania', capital: 'Tirana', famousPlace: 'Berat Castle' },
  { country: 'Algeria', capital: 'Algiers', famousPlace: 'Notre Dame d’Afrique' },
  { country: 'Andorra', capital: 'Andorra la Vella', famousPlace: 'Vallnord' },
  { country: 'Angola', capital: 'Luanda', famousPlace: 'Fortaleza de São Miguel' },
  { country: 'Argentina', capital: 'Buenos Aires', famousPlace: 'Iguazu Falls' },
  { country: 'Armenia', capital: 'Yerevan', famousPlace: 'Geghard Monastery' },
  { country: 'Australia', capital: 'Canberra', famousPlace: 'Sydney Opera House' },
  { country: 'Austria', capital: 'Vienna', famousPlace: 'Schönbrunn Palace' },
  { country: 'Azerbaijan', capital: 'Baku', famousPlace: 'Maiden Tower' },
  { country: 'Bahamas', capital: 'Nassau', famousPlace: 'Atlantis Paradise Island' },
  { country: 'Bahrain', capital: 'Manama', famousPlace: 'Bahrain Fort' },
  { country: 'Bangladesh', capital: 'Dhaka', famousPlace: 'Lalbagh Fort' },
  { country: 'Barbados', capital: 'Bridgetown', famousPlace: 'Harrison’s Cave' },
  { country: 'Belarus', capital: 'Minsk', famousPlace: 'Mir Castle' },
  { country: 'Belgium', capital: 'Brussels', famousPlace: 'Grand Place' },
  { country: 'Belize', capital: 'Belmopan', famousPlace: 'Great Blue Hole' },
  { country: 'Benin', capital: 'Porto-Novo', famousPlace: 'Pendjari National Park' },
  { country: 'Bhutan', capital: 'Thimphu', famousPlace: 'Paro Taktsang' },
  { country: 'Bolivia', capital: 'Sucre', famousPlace: 'Salar de Uyuni' },
  { country: 'Bosnia and Herzegovina', capital: 'Sarajevo', famousPlace: 'Stari Most' },
  { country: 'Botswana', capital: 'Gaborone', famousPlace: 'Okavango Delta' },
  { country: 'Brazil', capital: 'Brasília', famousPlace: 'Christ the Redeemer' },
  { country: 'Brunei', capital: 'Bandar Seri Begawan', famousPlace: 'Omar Ali Saifuddien Mosque' },
  { country: 'Bulgaria', capital: 'Sofia', famousPlace: 'Alexander Nevsky Cathedral' },
  { country: 'Burkina Faso', capital: 'Ouagadougou', famousPlace: 'Laongo Sculpture Symposium' },
  { country: 'Burundi', capital: 'Gitega', famousPlace: 'Rusizi National Park' },
  { country: 'Cabo Verde', capital: 'Praia', famousPlace: 'Fogo Volcano' },
  { country: 'Cambodia', capital: 'Phnom Penh', famousPlace: 'Angkor Wat' },
  { country: 'Cameroon', capital: 'Yaoundé', famousPlace: 'Waza National Park' },
  { country: 'Canada', capital: 'Ottawa', famousPlace: 'Niagara Falls' },
  { country: 'Central African Republic', capital: 'Bangui', famousPlace: 'Dzanga-Sangha Reserve' },
  { country: 'Chad', capital: "N'Djamena", famousPlace: 'Zakouma National Park' },
  { country: 'Chile', capital: 'Santiago', famousPlace: 'Easter Island' },
  { country: 'China', capital: 'Beijing', famousPlace: 'Great Wall of China' },
  { country: 'Colombia', capital: 'Bogotá', famousPlace: 'Cartagena Old Town' },
  { country: 'Comoros', capital: 'Moroni', famousPlace: 'Mount Karthala' },
  { country: 'Congo, Democratic Republic of the', capital: 'Kinshasa', famousPlace: 'Virunga National Park' },
  { country: 'Congo, Republic of the', capital: 'Brazzaville', famousPlace: 'Basilique Sainte-Anne' },
  { country: 'Costa Rica', capital: 'San José', famousPlace: 'Arenal Volcano' },
  { country: 'Croatia', capital: 'Zagreb', famousPlace: 'Plitvice Lakes' },
  { country: 'Cuba', capital: 'Havana', famousPlace: 'Malecón' },
  { country: 'Cyprus', capital: 'Nicosia', famousPlace: 'Kykkos Monastery' },
  { country: 'Czech Republic', capital: 'Prague', famousPlace: 'Charles Bridge' },
  { country: 'Denmark', capital: 'Copenhagen', famousPlace: 'Tivoli Gardens' },
  { country: 'Djibouti', capital: 'Djibouti (city)', famousPlace: 'Lake Assal' },
  { country: 'Dominica', capital: 'Roseau', famousPlace: 'Boiling Lake' },
  { country: 'Dominican Republic', capital: 'Santo Domingo', famousPlace: 'Punta Cana' },
  { country: 'East Timor (Timor-Leste)', capital: 'Dili', famousPlace: 'Cristo Rei' },
  { country: 'Ecuador', capital: 'Quito', famousPlace: 'Galápagos Islands' },
  { country: 'Egypt', capital: 'Cairo', famousPlace: 'Pyramids of Giza' },
  { country: 'El Salvador', capital: 'San Salvador', famousPlace: 'Joya de Cerén' },
  { country: 'Equatorial Guinea', capital: 'Malabo', famousPlace: 'Bioko Island' },
  { country: 'Eritrea', capital: 'Asmara', famousPlace: 'Dahlak Archipelago' },
  { country: 'Estonia', capital: 'Tallinn', famousPlace: 'Tallinn Old Town' },
  { country: 'Eswatini', capital: 'Mbabane', famousPlace: 'Mlilwane Wildlife Sanctuary' },
  { country: 'Ethiopia', capital: 'Addis Ababa', famousPlace: 'Lalibela Churches' },
  { country: 'Fiji', capital: 'Suva', famousPlace: 'Mamanuca Islands' },
  { country: 'Finland', capital: 'Helsinki', famousPlace: 'Suomenlinna' },
  { country: 'France', capital: 'Paris', famousPlace: 'Eiffel Tower' },
  { country: 'Gabon', capital: 'Libreville', famousPlace: 'Loango National Park' },
  { country: 'Gambia', capital: 'Banjul', famousPlace: 'Abuko Nature Reserve' },
  { country: 'Georgia', capital: 'Tbilisi', famousPlace: 'Narikala Fortress' },
  { country: 'Germany', capital: 'Berlin', famousPlace: 'Brandenburg Gate' },
  { country: 'Ghana', capital: 'Accra', famousPlace: 'Cape Coast Castle' },
  { country: 'Greece', capital: 'Athens', famousPlace: 'Acropolis' },
  { country: 'Grenada', capital: "St. George's", famousPlace: 'Grand Anse Beach' },
  { country: 'Guatemala', capital: 'Guatemala City', famousPlace: 'Tikal' },
  { country: 'Guinea', capital: 'Conakry', famousPlace: 'Îles de Los' },
  { country: 'Guinea-Bissau', capital: 'Bissau', famousPlace: 'Bijagos Archipelago' },
  { country: 'Guyana', capital: 'Georgetown', famousPlace: 'Kaieteur Falls' },
  { country: 'Haiti', capital: 'Port-au-Prince', famousPlace: 'Citadelle Laferrière' },
  { country: 'Honduras', capital: 'Tegucigalpa', famousPlace: 'Copán Ruins' },
  { country: 'Hungary', capital: 'Budapest', famousPlace: 'Buda Castle' },
  { country: 'Iceland', capital: 'Reykjavik', famousPlace: 'Blue Lagoon' },
  { country: 'India', capital: 'New Delhi', famousPlace: 'Taj Mahal' },
  { country: 'Indonesia', capital: 'Jakarta', famousPlace: 'Borobudur' },
  { country: 'Iran', capital: 'Tehran', famousPlace: 'Persepolis' },
  { country: 'Iraq', capital: 'Baghdad', famousPlace: 'Babylon' },
  { country: 'Ireland', capital: 'Dublin', famousPlace: 'Cliffs of Moher' },
  { country: 'Israel', capital: 'Jerusalem', famousPlace: 'Western Wall' },
  { country: 'Italy', capital: 'Rome', famousPlace: 'Colosseum' },
  { country: 'Jamaica', capital: 'Kingston', famousPlace: 'Dunn’s River Falls' },
  { country: 'Japan', capital: 'Tokyo', famousPlace: 'Mount Fuji' },
  { country: 'Jordan', capital: 'Amman', famousPlace: 'Petra' },
  { country: 'Kazakhstan', capital: 'Nur-Sultan', famousPlace: 'Bayterek Tower' },
  { country: 'Kenya', capital: 'Nairobi', famousPlace: 'Maasai Mara' },
  { country: 'Kiribati', capital: 'Tarawa', famousPlace: 'Phoenix Islands' },
  { country: 'Korea, North', capital: 'Pyongyang', famousPlace: 'Juche Tower' },
  { country: 'Korea, South', capital: 'Seoul', famousPlace: 'Gyeongbokgung Palace' },
  { country: 'Kosovo', capital: 'Pristina', famousPlace: 'Germia Park' },
  { country: 'Kuwait', capital: 'Kuwait City', famousPlace: 'Kuwait Towers' },
  { country: 'Kyrgyzstan', capital: 'Bishkek', famousPlace: 'Issyk-Kul Lake' },
  { country: 'Laos', capital: 'Vientiane', famousPlace: 'Pha That Luang' },
  { country: 'Latvia', capital: 'Riga', famousPlace: 'Old Town Riga' },
  { country: 'Lebanon', capital: 'Beirut', famousPlace: 'Baalbek' },
  { country: 'Lesotho', capital: 'Maseru', famousPlace: 'Maletsunyane Falls' },
  { country: 'Liberia', capital: 'Monrovia', famousPlace: 'Sapo National Park' },
  { country: 'Libya', capital: 'Tripoli', famousPlace: 'Leptis Magna' },
  { country: 'Liechtenstein', capital: 'Vaduz', famousPlace: 'Vaduz Castle' },
  { country: 'Lithuania', capital: 'Vilnius', famousPlace: 'Trakai Island Castle' },
  { country: 'Luxembourg', capital: 'Luxembourg (city)', famousPlace: 'Vianden Castle' },
  { country: 'Madagascar', capital: 'Antananarivo', famousPlace: 'Avenue of the Baobabs' },
  { country: 'Malawi', capital: 'Lilongwe', famousPlace: 'Lake Malawi' },
  { country: 'Malaysia', capital: 'Kuala Lumpur', famousPlace: 'Petronas Towers' },
  { country: 'Maldives', capital: 'Malé', famousPlace: 'Banana Reef' },
  { country: 'Mali', capital: 'Bamako', famousPlace: 'Djenné Mosque' },
  { country: 'Malta', capital: 'Valletta', famousPlace: 'St. John’s Co-Cathedral' },
  { country: 'Marshall Islands', capital: 'Majuro', famousPlace: 'Bikini Atoll' },
  { country: 'Mauritania', capital: 'Nouakchott', famousPlace: 'Banc d’Arguin National Park' },
  { country: 'Mauritius', capital: 'Port Louis', famousPlace: 'Le Morne Brabant' },
  { country: 'Mexico', capital: 'Mexico City', famousPlace: 'Chichen Itza' },
  { country: 'Micronesia', capital: 'Palikir', famousPlace: 'Nan Madol' },
  { country: 'Moldova', capital: 'Chișinău', famousPlace: 'Orheiul Vechi' },
  { country: 'Monaco', capital: 'Monaco', famousPlace: 'Monte Carlo Casino' },
  { country: 'Mongolia', capital: 'Ulaanbaatar', famousPlace: 'Gorkhi-Terelj National Park' },
  { country: 'Montenegro', capital: 'Podgorica', famousPlace: 'Bay of Kotor' },
  { country: 'Morocco', capital: 'Rabat', famousPlace: 'Jemaa el-Fnaa' },
  { country: 'Mozambique', capital: 'Maputo', famousPlace: 'Bazaruto Archipelago' },
  { country: 'Myanmar (Burma)', capital: 'Naypyidaw', famousPlace: 'Bagan' },
  { country: 'Namibia', capital: 'Windhoek', famousPlace: 'Sossusvlei' },
  { country: 'Nauru', capital: 'Yaren District', famousPlace: 'Anibare Bay' },
  { country: 'Nepal', capital: 'Kathmandu', famousPlace: 'Mount Everest' },
  { country: 'Netherlands', capital: 'Amsterdam', famousPlace: 'Keukenhof Gardens' },
  { country: 'New Zealand', capital: 'Wellington', famousPlace: 'Milford Sound' },
  { country: 'Nicaragua', capital: 'Managua', famousPlace: 'Ometepe Island' },
  { country: 'Niger', capital: 'Niamey', famousPlace: 'Aïr Mountains' },
  { country: 'Nigeria', capital: 'Abuja', famousPlace: 'Zuma Rock' },
  { country: 'North Macedonia', capital: 'Skopje', famousPlace: 'Lake Ohrid' },
  { country: 'Norway', capital: 'Oslo', famousPlace: 'Geirangerfjord' },
  { country: 'Oman', capital: 'Muscat', famousPlace: 'Sultan Qaboos Grand Mosque' },
  { country: 'Pakistan', capital: 'Islamabad', famousPlace: 'Badshahi Mosque' },
  { country: 'Palau', capital: 'Ngerulmud', famousPlace: 'Rock Islands' },
  { country: 'Palestine', capital: 'Ramallah', famousPlace: 'Church of the Nativity' },
  { country: 'Panama', capital: 'Panama City', famousPlace: 'Panama Canal' },
  { country: 'Papua New Guinea', capital: 'Port Moresby', famousPlace: 'Kokoda Track' },
  { country: 'Paraguay', capital: 'Asunción', famousPlace: 'Itaipu Dam' },
  { country: 'Peru', capital: 'Lima', famousPlace: 'Machu Picchu' },
  { country: 'Philippines', capital: 'Manila', famousPlace: 'Chocolate Hills' },
  { country: 'Poland', capital: 'Warsaw', famousPlace: 'Wieliczka Salt Mine' },
  { country: 'Portugal', capital: 'Lisbon', famousPlace: 'Belém Tower' },
  { country: 'Qatar', capital: 'Doha', famousPlace: 'Museum of Islamic Art' },
  { country: 'Romania', capital: 'Bucharest', famousPlace: 'Bran Castle' },
  { country: 'Russia', capital: 'Moscow', famousPlace: 'Red Square' },
  { country: 'Rwanda', capital: 'Kigali', famousPlace: 'Volcanoes National Park' },
  { country: 'Saint Kitts and Nevis', capital: 'Basseterre', famousPlace: 'Brimstone Hill Fortress' },
  { country: 'Saint Lucia', capital: 'Castries', famousPlace: 'Pitons' },
  { country: 'Saint Vincent and the Grenadines', capital: 'Kingstown', famousPlace: 'La Soufrière' },
  { country: 'Samoa', capital: 'Apia', famousPlace: 'To Sua Ocean Trench' },
  { country: 'San Marino', capital: 'San Marino', famousPlace: 'Guaita Tower' },
  { country: 'Sao Tome and Principe', capital: 'São Tomé', famousPlace: 'Pico Cão Grande' },
  { country: 'Saudi Arabia', capital: 'Riyadh', famousPlace: 'Masmak Fortress' },
  { country: 'Senegal', capital: 'Dakar', famousPlace: 'Gorée Island' },
  { country: 'Serbia', capital: 'Belgrade', famousPlace: 'Belgrade Fortress' },
  { country: 'Seychelles', capital: 'Victoria', famousPlace: 'Anse Source d’Argent' },
  { country: 'Sierra Leone', capital: 'Freetown', famousPlace: 'Tacugama Chimpanzee Sanctuary' },
  { country: 'Singapore', capital: 'Singapore', famousPlace: 'Marina Bay Sands' },
  { country: 'Slovakia', capital: 'Bratislava', famousPlace: 'Bratislava Castle' },
  { country: 'Slovenia', capital: 'Ljubljana', famousPlace: 'Lake Bled' },
  { country: 'Solomon Islands', capital: 'Honiara', famousPlace: 'Marovo Lagoon' },
  { country: 'Somalia', capital: 'Mogadishu', famousPlace: 'Laas Geel' },
  { country: 'South Africa', capital: 'Pretoria', famousPlace: 'Table Mountain' },
  { country: 'South Sudan', capital: 'Juba', famousPlace: 'Boma National Park' },
  { country: 'Spain', capital: 'Madrid', famousPlace: 'Sagrada Familia' },
  { country: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte', famousPlace: 'Sigiriya' },
  { country: 'Sudan', capital: 'Khartoum', famousPlace: 'Meroë Pyramids' },
  { country: 'Suriname', capital: 'Paramaribo', famousPlace: 'Central Suriname Nature Reserve' },
  { country: 'Sweden', capital: 'Stockholm', famousPlace: 'Vasa Museum' },
  { country: 'Switzerland', capital: 'Bern', famousPlace: 'Matterhorn' },
  { country: 'Syria', capital: 'Damascus', famousPlace: 'Umayyad Mosque' },
  { country: 'Taiwan', capital: 'Taipei', famousPlace: 'Taipei 101' },
  { country: 'Tajikistan', capital: 'Dushanbe', famousPlace: 'Iskanderkul Lake' },
  { country: 'Tanzania', capital: 'Dodoma', famousPlace: 'Serengeti National Park' },
  { country: 'Thailand', capital: 'Bangkok', famousPlace: 'Grand Palace' },
  { country: 'Togo', capital: 'Lomé', famousPlace: 'Koutammakou' },
  { country: 'Tonga', capital: 'Nukuʻalofa', famousPlace: 'Mapu a Vaea Blowholes' },
  { country: 'Trinidad and Tobago', capital: 'Port of Spain', famousPlace: 'Maracas Beach' },
  { country: 'Tunisia', capital: 'Tunis', famousPlace: 'Amphitheatre of El Jem' },
  { country: 'Turkey', capital: 'Ankara', famousPlace: 'Hagia Sophia' },
  { country: 'Turkmenistan', capital: 'Ashgabat', famousPlace: 'Darvaza Gas Crater' },
  { country: 'Tuvalu', capital: 'Funafuti', famousPlace: 'Funafuti Conservation Area' },
  { country: 'Uganda', capital: 'Kampala', famousPlace: 'Bwindi Impenetrable Forest' },
  { country: 'Ukraine', capital: 'Kyiv', famousPlace: 'Chernobyl' },
  { country: 'United Arab Emirates', capital: 'Abu Dhabi', famousPlace: 'Burj Khalifa' },
  { country: 'United Kingdom', capital: 'London', famousPlace: 'Big Ben' },
  { country: 'United States', capital: 'Washington, D.C.', famousPlace: 'Statue of Liberty' },
  { country: 'Uruguay', capital: 'Montevideo', famousPlace: 'Punta del Este' },
  { country: 'Uzbekistan', capital: 'Tashkent', famousPlace: 'Registan' },
  { country: 'Vanuatu', capital: 'Port Vila', famousPlace: 'Mount Yasur' },
  { country: 'Vatican City', capital: 'Vatican City', famousPlace: 'St. Peter’s Basilica' },
  { country: 'Venezuela', capital: 'Caracas', famousPlace: 'Angel Falls' },
  { country: 'Vietnam', capital: 'Hanoi', famousPlace: 'Ha Long Bay' },
  { country: 'Yemen', capital: 'Sana\'a', famousPlace: 'Socotra Island' },
  { country: 'Zambia', capital: 'Lusaka', famousPlace: 'Victoria Falls' },
  { country: 'Zimbabwe', capital: 'Harare', famousPlace: 'Hwange National Park' }
];

app.use(cors());

app.get('/api/items', (req, res) => {
  const page = parseInt(req.query.page, 10) || 1;
  const limit = parseInt(req.query.limit, 10) || 10;
  const total = items.length;
  const totalPages = Math.ceil(total / limit);
  const start = (page - 1) * limit;
  const end = start + limit;
  const data = items.slice(start, end);

  res.json({
    data,
    total,
    page,
    limit,
    totalPages
  });
});

app.listen(PORT, () => {
  console.log(`API server running at http://localhost:${PORT}/api/items`);
});
