const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3010;
// Serve static files (frontend) from public folder
app.use(express.static(path.join(__dirname, 'public')));

// Redirect root URL to index.html for user-friendly UI
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// In-memory data: All countries, capitals, and a famous place
const items = [
  { country: 'Afghanistan', capital: 'Kabul', place: 'Blue Mosque' },
  { country: 'Albania', capital: 'Tirana', place: 'Berat Castle' },
  { country: 'Algeria', capital: 'Algiers', place: 'Notre Dame d’Afrique' },
  { country: 'Andorra', capital: 'Andorra la Vella', place: 'Vallnord' },
  { country: 'Angola', capital: 'Luanda', place: 'Fortaleza de São Miguel' },
  { country: 'Antigua and Barbuda', capital: 'Saint John’s', place: 'Nelson’s Dockyard' },
  { country: 'Argentina', capital: 'Buenos Aires', place: 'Iguazu Falls' },
  { country: 'Armenia', capital: 'Yerevan', place: 'Geghard Monastery' },
  { country: 'Australia', capital: 'Canberra', place: 'Sydney Opera House' },
  { country: 'Austria', capital: 'Vienna', place: 'Schönbrunn Palace' },
  { country: 'Azerbaijan', capital: 'Baku', place: 'Maiden Tower' },
  { country: 'Bahamas', capital: 'Nassau', place: 'Atlantis Paradise Island' },
  { country: 'Bahrain', capital: 'Manama', place: 'Qal’at al-Bahrain' },
  { country: 'Bangladesh', capital: 'Dhaka', place: 'Lalbagh Fort' },
  { country: 'Barbados', capital: 'Bridgetown', place: 'Harrison’s Cave' },
  { country: 'Belarus', capital: 'Minsk', place: 'Mir Castle' },
  { country: 'Belgium', capital: 'Brussels', place: 'Grand Place' },
  { country: 'Belize', capital: 'Belmopan', place: 'Great Blue Hole' },
  { country: 'Benin', capital: 'Porto-Novo', place: 'Pendjari National Park' },
  { country: 'Bhutan', capital: 'Thimphu', place: 'Paro Taktsang' },
  { country: 'Bolivia', capital: 'Sucre', place: 'Salar de Uyuni' },
  { country: 'Bosnia and Herzegovina', capital: 'Sarajevo', place: 'Stari Most' },
  { country: 'Botswana', capital: 'Gaborone', place: 'Okavango Delta' },
  { country: 'Brazil', capital: 'Brasília', place: 'Christ the Redeemer' },
  { country: 'Brunei', capital: 'Bandar Seri Begawan', place: 'Omar Ali Saifuddien Mosque' },
  { country: 'Bulgaria', capital: 'Sofia', place: 'Alexander Nevsky Cathedral' },
  { country: 'Burkina Faso', capital: 'Ouagadougou', place: 'Laongo Sculpture Symposium' },
  { country: 'Burundi', capital: 'Gitega', place: 'Rusizi National Park' },
  { country: 'Cabo Verde', capital: 'Praia', place: 'Fogo Volcano' },
  { country: 'Cambodia', capital: 'Phnom Penh', place: 'Angkor Wat' },
  { country: 'Cameroon', capital: 'Yaoundé', place: 'Waza National Park' },
  { country: 'Canada', capital: 'Ottawa', place: 'Niagara Falls' },
  { country: 'Central African Republic', capital: 'Bangui', place: 'Dzanga-Sangha Reserve' },
  { country: 'Chad', capital: 'N’Djamena', place: 'Zakouma National Park' },
  { country: 'Chile', capital: 'Santiago', place: 'Easter Island' },
  { country: 'China', capital: 'Beijing', place: 'Great Wall of China' },
  { country: 'Colombia', capital: 'Bogotá', place: 'Cartagena Old Town' },
  { country: 'Comoros', capital: 'Moroni', place: 'Mount Karthala' },
  { country: 'Congo (Congo-Brazzaville)', capital: 'Brazzaville', place: 'Basilique Sainte-Anne' },
  { country: 'Costa Rica', capital: 'San José', place: 'Arenal Volcano' },
  { country: 'Croatia', capital: 'Zagreb', place: 'Plitvice Lakes' },
  { country: 'Cuba', capital: 'Havana', place: 'Malecón' },
  { country: 'Cyprus', capital: 'Nicosia', place: 'Kyrenia Castle' },
  { country: 'Czechia', capital: 'Prague', place: 'Charles Bridge' },
  { country: 'Democratic Republic of the Congo', capital: 'Kinshasa', place: 'Virunga National Park' },
  { country: 'Denmark', capital: 'Copenhagen', place: 'Tivoli Gardens' },
  { country: 'Djibouti', capital: 'Djibouti', place: 'Lake Assal' },
  { country: 'Dominica', capital: 'Roseau', place: 'Boiling Lake' },
  { country: 'Dominican Republic', capital: 'Santo Domingo', place: 'Pico Duarte' },
  { country: 'Ecuador', capital: 'Quito', place: 'Galápagos Islands' },
  { country: 'Egypt', capital: 'Cairo', place: 'Pyramids of Giza' },
  { country: 'El Salvador', capital: 'San Salvador', place: 'Joya de Cerén' },
  { country: 'Equatorial Guinea', capital: 'Malabo', place: 'Bioko Island' },
  { country: 'Eritrea', capital: 'Asmara', place: 'Dahlak Archipelago' },
  { country: 'Estonia', capital: 'Tallinn', place: 'Tallinn Old Town' },
  { country: 'Eswatini', capital: 'Mbabane', place: 'Mlilwane Wildlife Sanctuary' },
  { country: 'Ethiopia', capital: 'Addis Ababa', place: 'Lalibela' },
  { country: 'Fiji', capital: 'Suva', place: 'Mamanuca Islands' },
  { country: 'Finland', capital: 'Helsinki', place: 'Suomenlinna' },
  { country: 'France', capital: 'Paris', place: 'Eiffel Tower' },
  { country: 'Gabon', capital: 'Libreville', place: 'Loango National Park' },
  { country: 'Gambia', capital: 'Banjul', place: 'Kunta Kinteh Island' },
  { country: 'Georgia', capital: 'Tbilisi', place: 'Narikala Fortress' },
  { country: 'Germany', capital: 'Berlin', place: 'Brandenburg Gate' },
  { country: 'Ghana', capital: 'Accra', place: 'Cape Coast Castle' },
  { country: 'Greece', capital: 'Athens', place: 'Acropolis' },
  { country: 'Grenada', capital: 'Saint George’s', place: 'Grand Anse Beach' },
  { country: 'Guatemala', capital: 'Guatemala City', place: 'Tikal' },
  { country: 'Guinea', capital: 'Conakry', place: 'Mount Nimba' },
  { country: 'Guinea-Bissau', capital: 'Bissau', place: 'Bijagos Archipelago' },
  { country: 'Guyana', capital: 'Georgetown', place: 'Kaieteur Falls' },
  { country: 'Haiti', capital: 'Port-au-Prince', place: 'Citadelle Laferrière' },
  { country: 'Honduras', capital: 'Tegucigalpa', place: 'Copán Ruins' },
  { country: 'Hungary', capital: 'Budapest', place: 'Buda Castle' },
  { country: 'Iceland', capital: 'Reykjavík', place: 'Blue Lagoon' },
  { country: 'India', capital: 'New Delhi', place: 'Taj Mahal' },
  { country: 'Indonesia', capital: 'Jakarta', place: 'Borobudur' },
  { country: 'Iran', capital: 'Tehran', place: 'Persepolis' },
  { country: 'Iraq', capital: 'Baghdad', place: 'Babylon' },
  { country: 'Ireland', capital: 'Dublin', place: 'Cliffs of Moher' },
  { country: 'Israel', capital: 'Jerusalem', place: 'Western Wall' },
  { country: 'Italy', capital: 'Rome', place: 'Colosseum' },
  { country: 'Jamaica', capital: 'Kingston', place: 'Dunn’s River Falls' },
  { country: 'Japan', capital: 'Tokyo', place: 'Mount Fuji' },
  { country: 'Jordan', capital: 'Amman', place: 'Petra' },
  { country: 'Kazakhstan', capital: 'Astana', place: 'Bayterek Tower' },
  { country: 'Kenya', capital: 'Nairobi', place: 'Maasai Mara' },
  { country: 'Kiribati', capital: 'Tarawa', place: 'Phoenix Islands' },
  { country: 'Kuwait', capital: 'Kuwait City', place: 'Kuwait Towers' },
  { country: 'Kyrgyzstan', capital: 'Bishkek', place: 'Issyk-Kul Lake' },
  { country: 'Laos', capital: 'Vientiane', place: 'Pha That Luang' },
  { country: 'Latvia', capital: 'Riga', place: 'Riga Old Town' },
  { country: 'Lebanon', capital: 'Beirut', place: 'Baalbek' },
  { country: 'Lesotho', capital: 'Maseru', place: 'Maletsunyane Falls' },
  { country: 'Liberia', capital: 'Monrovia', place: 'Sapo National Park' },
  { country: 'Libya', capital: 'Tripoli', place: 'Leptis Magna' },
  { country: 'Liechtenstein', capital: 'Vaduz', place: 'Vaduz Castle' },
  { country: 'Lithuania', capital: 'Vilnius', place: 'Trakai Island Castle' },
  { country: 'Luxembourg', capital: 'Luxembourg', place: 'Vianden Castle' },
  { country: 'Madagascar', capital: 'Antananarivo', place: 'Avenue of the Baobabs' },
  { country: 'Malawi', capital: 'Lilongwe', place: 'Lake Malawi' },
  { country: 'Malaysia', capital: 'Kuala Lumpur', place: 'Petronas Towers' },
  { country: 'Maldives', capital: 'Malé', place: 'Malé Friday Mosque' },
  { country: 'Mali', capital: 'Bamako', place: 'Djenné Mosque' },
  { country: 'Malta', capital: 'Valletta', place: 'St. John’s Co-Cathedral' },
  { country: 'Marshall Islands', capital: 'Majuro', place: 'Bikini Atoll' },
  { country: 'Mauritania', capital: 'Nouakchott', place: 'Banc d’Arguin National Park' },
  { country: 'Mauritius', capital: 'Port Louis', place: 'Le Morne Brabant' },
  { country: 'Mexico', capital: 'Mexico City', place: 'Chichen Itza' },
  { country: 'Micronesia', capital: 'Palikir', place: 'Nan Madol' },
  { country: 'Moldova', capital: 'Chișinău', place: 'Orheiul Vechi' },
  { country: 'Monaco', capital: 'Monaco', place: 'Monte Carlo Casino' },
  { country: 'Mongolia', capital: 'Ulaanbaatar', place: 'Gorkhi-Terelj National Park' },
  { country: 'Montenegro', capital: 'Podgorica', place: 'Bay of Kotor' },
  { country: 'Morocco', capital: 'Rabat', place: 'Jemaa el-Fnaa' },
  { country: 'Mozambique', capital: 'Maputo', place: 'Bazaruto Archipelago' },
  { country: 'Myanmar', capital: 'Naypyidaw', place: 'Bagan' },
  { country: 'Namibia', capital: 'Windhoek', place: 'Sossusvlei' },
  { country: 'Nauru', capital: 'Yaren', place: 'Anibare Bay' },
  { country: 'Nepal', capital: 'Kathmandu', place: 'Mount Everest' },
  { country: 'Netherlands', capital: 'Amsterdam', place: 'Rijksmuseum' },
  { country: 'New Zealand', capital: 'Wellington', place: 'Milford Sound' },
  { country: 'Nicaragua', capital: 'Managua', place: 'Ometepe Island' },
  { country: 'Niger', capital: 'Niamey', place: 'Aïr Mountains' },
  { country: 'Nigeria', capital: 'Abuja', place: 'Zuma Rock' },
  { country: 'North Korea', capital: 'Pyongyang', place: 'Juche Tower' },
  { country: 'North Macedonia', capital: 'Skopje', place: 'Lake Ohrid' },
  { country: 'Norway', capital: 'Oslo', place: 'Geirangerfjord' },
  { country: 'Oman', capital: 'Muscat', place: 'Sultan Qaboos Grand Mosque' },
  { country: 'Pakistan', capital: 'Islamabad', place: 'Badshahi Mosque' },
  { country: 'Palau', capital: 'Ngerulmud', place: 'Rock Islands' },
  { country: 'Palestine', capital: 'Ramallah', place: 'Church of the Nativity' },
  { country: 'Panama', capital: 'Panama City', place: 'Panama Canal' },
  { country: 'Papua New Guinea', capital: 'Port Moresby', place: 'Kokoda Track' },
  { country: 'Paraguay', capital: 'Asunción', place: 'Itaipu Dam' },
  { country: 'Peru', capital: 'Lima', place: 'Machu Picchu' },
  { country: 'Philippines', capital: 'Manila', place: 'Chocolate Hills' },
  { country: 'Poland', capital: 'Warsaw', place: 'Wawel Castle' },
  { country: 'Portugal', capital: 'Lisbon', place: 'Belém Tower' },
  { country: 'Qatar', capital: 'Doha', place: 'Museum of Islamic Art' },
  { country: 'Romania', capital: 'Bucharest', place: 'Bran Castle' },
  { country: 'Russia', capital: 'Moscow', place: 'Red Square' },
  { country: 'Rwanda', capital: 'Kigali', place: 'Volcanoes National Park' },
  { country: 'Saint Kitts and Nevis', capital: 'Basseterre', place: 'Brimstone Hill Fortress' },
  { country: 'Saint Lucia', capital: 'Castries', place: 'Pitons' },
  { country: 'Saint Vincent and the Grenadines', capital: 'Kingstown', place: 'La Soufrière' },
  { country: 'Samoa', capital: 'Apia', place: 'To Sua Ocean Trench' },
  { country: 'San Marino', capital: 'San Marino', place: 'Guaita Tower' },
  { country: 'Sao Tome and Principe', capital: 'São Tomé', place: 'Obô National Park' },
  { country: 'Saudi Arabia', capital: 'Riyadh', place: 'Masmak Fortress' },
  { country: 'Senegal', capital: 'Dakar', place: 'Gorée Island' },
  { country: 'Serbia', capital: 'Belgrade', place: 'Kalemegdan Fortress' },
  { country: 'Seychelles', capital: 'Victoria', place: 'Anse Source d’Argent' },
  { country: 'Sierra Leone', capital: 'Freetown', place: 'Tacugama Chimpanzee Sanctuary' },
  { country: 'Singapore', capital: 'Singapore', place: 'Marina Bay Sands' },
  { country: 'Slovakia', capital: 'Bratislava', place: 'Bratislava Castle' },
  { country: 'Slovenia', capital: 'Ljubljana', place: 'Lake Bled' },
  { country: 'Solomon Islands', capital: 'Honiara', place: 'Mbonege Beach' },
  { country: 'Somalia', capital: 'Mogadishu', place: 'Laas Geel' },
  { country: 'South Africa', capital: 'Pretoria', place: 'Table Mountain' },
  { country: 'South Korea', capital: 'Seoul', place: 'Gyeongbokgung Palace' },
  { country: 'South Sudan', capital: 'Juba', place: 'Boma National Park' },
  { country: 'Spain', capital: 'Madrid', place: 'Sagrada Família' },
  { country: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte', place: 'Sigiriya' },
  { country: 'Sudan', capital: 'Khartoum', place: 'Meroë Pyramids' },
  { country: 'Suriname', capital: 'Paramaribo', place: 'Central Suriname Nature Reserve' },
  { country: 'Sweden', capital: 'Stockholm', place: 'Vasa Museum' },
  { country: 'Switzerland', capital: 'Bern', place: 'Matterhorn' },
  { country: 'Syria', capital: 'Damascus', place: 'Umayyad Mosque' },
  { country: 'Taiwan', capital: 'Taipei', place: 'Taipei 101' },
  { country: 'Tajikistan', capital: 'Dushanbe', place: 'Iskanderkul Lake' },
  { country: 'Tanzania', capital: 'Dodoma', place: 'Mount Kilimanjaro' },
  { country: 'Thailand', capital: 'Bangkok', place: 'Grand Palace' },
  { country: 'Timor-Leste', capital: 'Dili', place: 'Cristo Rei' },
  { country: 'Togo', capital: 'Lomé', place: 'Koutammakou' },
  { country: 'Tonga', capital: 'Nukuʻalofa', place: 'Haʻamonga ʻa Maui' },
  { country: 'Trinidad and Tobago', capital: 'Port of Spain', place: 'Maracas Bay' },
  { country: 'Tunisia', capital: 'Tunis', place: 'Amphitheatre of El Jem' },
  { country: 'Turkey', capital: 'Ankara', place: 'Hagia Sophia' },
  { country: 'Turkmenistan', capital: 'Ashgabat', place: 'Darvaza Gas Crater' },
  { country: 'Tuvalu', capital: 'Funafuti', place: 'Funafuti Conservation Area' },
  { country: 'Uganda', capital: 'Kampala', place: 'Bwindi Impenetrable Forest' },
  { country: 'Ukraine', capital: 'Kyiv', place: 'Saint Sophia Cathedral' },
  { country: 'United Arab Emirates', capital: 'Abu Dhabi', place: 'Burj Khalifa' },
  { country: 'United Kingdom', capital: 'London', place: 'Big Ben' },
  { country: 'United States', capital: 'Washington, D.C.', place: 'Statue of Liberty' },
  { country: 'Uruguay', capital: 'Montevideo', place: 'Punta del Este' },
  { country: 'Uzbekistan', capital: 'Tashkent', place: 'Registan' },
  { country: 'Vanuatu', capital: 'Port Vila', place: 'Mount Yasur' },
  { country: 'Vatican City', capital: 'Vatican City', place: 'St. Peter’s Basilica' },
  { country: 'Venezuela', capital: 'Caracas', place: 'Angel Falls' },
  { country: 'Vietnam', capital: 'Hanoi', place: 'Ha Long Bay' },
  { country: 'Yemen', capital: 'Sana’a', place: 'Old City of Sana’a' },
  { country: 'Zambia', capital: 'Lusaka', place: 'Victoria Falls' },
  { country: 'Zimbabwe', capital: 'Harare', place: 'Great Zimbabwe' }
].map((item, idx) => ({ id: idx + 1, ...item }));

app.use(cors());

app.get('/api/items', (req, res) => {
  const page = parseInt(req.query.page, 10) || 1;
  const pageSize = parseInt(req.query.pageSize, 10) || 10;
  let filtered = items;
  if (req.query.country) {
    filtered = filtered.filter(item => item.country.toLowerCase().includes(req.query.country.toLowerCase()));
  }
  if (req.query.capital) {
    filtered = filtered.filter(item => item.capital.toLowerCase().includes(req.query.capital.toLowerCase()));
  }
  if (req.query.place) {
    filtered = filtered.filter(item => item.place.toLowerCase().includes(req.query.place.toLowerCase()));
  }
  const total = filtered.length;
  const totalPages = Math.ceil(total / pageSize);
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  const paged = filtered.slice(start, end);
  res.json({
    items: paged,
    total,
    page,
    pageSize,
    totalPages
  });
});

app.listen(PORT, () => {
  console.log(`API server running at http://localhost:${PORT}/api/items`);
});